spring.application.name=spring-first-ai

server.port=8080

# --- Ollama (PRIMARY / ACTIVE) ---
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=codellama
spring.ai.ollama.chat.options.temperature=0.7

# --- Disable unused models so Spring doesn't get confused ---
#spring.ai.openai.chat.enabled=false
#spring.ai.google.genai.chat.enabled=false

# Keep these keys so Spring doesn't fail on missing properties
#spring.ai.openai.api-key=dummy
#spring.ai.google.genai.api-key=AQ.Ab8RN6J48Njb73fD8-TaJtzkbJhPQ5ADGiHiHyo8U33Q0M0EOg
#spring.ai.google.genai.chat.options.model=gemini-2.0-flash

spring.main.allow-bean-definition-overriding=true
